version: "3"

services:

    database:
        image: postgres:9.6.23-stretch
        restart: always
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: root
            POSTGRES_DB: command_bot_dev